before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction
php:
  - 5.5
  - 5.6
  - 7.0
language: php
matrix: 
  allow_failures: 
  - php: hhvm
addons:
  code_climate:
      repo_token: 